### ISSUE TITLE
Не создано исключение для лимита

### ISSUE THREAD

**Issue by UsaevaElina** [UsaevaElina/javaqa-team#11]
# Описание
При создании объекта, в котором лимит отрицательное число, должно выкидываться исключение

# Локализация дефекта
https://github.com/UsaevaElina/javaqa-team/blob/e34438cd78d845ada2b91dfa8aab3b6f236b7269/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20

# Шаги воспроизведения

1. Создать объект тестируемого класса с начальным значениями: initialBalance = 5_000, creditLimit = -8_000, ставка 10

*Ожидаемый результат:* На экран выводится сообщение "Лимит не должен быть отрицательным, а у вас: -8_000"
*Фактический результат:* Объект тестируемого класса создался успешно

# Тест
https://github.com/UsaevaElina/javaqa-team/blob/e34438cd78d845ada2b91dfa8aab3b6f236b7269/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L125

# Скриншот
![image](https://user-images.githubusercontent.com/125297595/235341643-768c7d09-6bba-4879-aa22-7addadcadf13.png)

# Окружение
* **Операционная система:** Windows 11 22H2
*  **IDEA**  IntelliJ IDEA 2022.3.2 (Community Edition)
*  **JAVA** OpenJDK 11

**Comment by Dmitryi1987** [comment]
Исправлено!
