### ISSUE TITLE
Начисляются проценты на положительное число

### ISSUE THREAD

**Issue by UsaevaElina** [UsaevaElina/javaqa-team#12]
# Описание
Начисляются проценты, если сумма баланса равна положительному числу

# Локализация дефекта
https://github.com/UsaevaElina/javaqa-team/blob/e34438cd78d845ada2b91dfa8aab3b6f236b7269/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L83

# Шаги воспроизведения

1. Создать объект тестируемого класса с начальным значениями: initialBalance = 200, creditLimit = 5_000, ставка 15

*Ожидаемый результат:* Проценты не начисляются, потому что сумма баланса равна положительному числу
*Фактический результат:* Проценты начисляются

# Тест
https://github.com/UsaevaElina/javaqa-team/blob/e34438cd78d845ada2b91dfa8aab3b6f236b7269/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L150

# Скриншот
![image](https://user-images.githubusercontent.com/125297595/235341802-1dd79d44-5413-40bf-87e4-1ae0b6cf5222.png)

# Окружение
* **Операционная система:** Windows 11 22H2
*  **IDEA**  IntelliJ IDEA 2022.3.2 (Community Edition)
*  **JAVA** OpenJDK 11

**Comment by Dmitryi1987** [comment]
Исправлено!
