### ISSUE TITLE
При покупке на сумму меньше суммы баланса, итоговый баланс считается отрицательным

### ISSUE THREAD

**Issue by UsaevaElina** [UsaevaElina/javaqa-team#7]
# Описание
При покупке на сумму меньше суммы баланса (в моем примере покупка на сумму 5_000, изначальный баланс 6_000), сумма кредитного лимита не должна затрагиваться и в итоге должна быть положительная сумма. Но указывается отрицательная (сумма баланса равна -5_000)

# Локализация дефекта
https://github.com/UsaevaElina/javaqa-team/blob/3cd5db5c8b1aadce7a8419dfda1bab71b24aad50/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L41

# Шаги воспроизведения

1. Создать объект тестируемого класса с начальным значениями: initialBalance = 6_000, creditLimit = 8_000, rate = 10
2. Заплатить на 5_000

*Ожидаемый результат:* В результате выполнения теста сумма остатка на балансе = 1_000
*Фактический результат:* В результате выполнения теста сумма остатка на балансе = -5_000

# Тест
https://github.com/UsaevaElina/javaqa-team/blob/e34438cd78d845ada2b91dfa8aab3b6f236b7269/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L48

# Скриншот
![image](https://user-images.githubusercontent.com/125297595/235339631-49d3732b-dce3-4dde-8bae-f774b0b77c82.png)

# Окружение
* **Операционная система:** Windows 11 22H2
*  **IDEA**  IntelliJ IDEA 2022.3.2 (Community Edition)
*  **JAVA** OpenJDK 11

**Comment by Dmitryi1987** [comment]
Исправлено!
