### ISSUE TITLE
Возможно оплатить сумму покупки, превышающую сумму на балансе и в лимите

### ISSUE THREAD

**Issue by UsaevaElina** [UsaevaElina/javaqa-team#9]
# Описание
Возможно совершить покупку, превышающую сумму баланса и превышающую сумму лимита (в моем примере покупка на сумму 13_001, изначальный баланс 5_000, сумма лимита 8_000), 

# Локализация дефекта
https://github.com/UsaevaElina/javaqa-team/blob/3cd5db5c8b1aadce7a8419dfda1bab71b24aad50/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L41

# Шаги воспроизведения

1. Создать объект тестируемого класса с начальным значениями: initialBalance = 5_000, creditLimit = 8_000, rate = 10
2. Заплатить на 13_001

*Ожидаемый результат:* В результате выполнения теста сумма остатка на балансе не должна поменяться, операция должна завершиться вернув false
*Фактический результат:* В результате выполнения теста сумма остатка на балансе = -13_001

# Тест
https://github.com/UsaevaElina/javaqa-team/blob/e34438cd78d845ada2b91dfa8aab3b6f236b7269/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L82

# Скриншот
![image](https://user-images.githubusercontent.com/125297595/235341291-60b6d0c7-c7cf-4fc2-8d50-8ceb570fd1ae.png)

# Окружение
* **Операционная система:** Windows 11 22H2
*  **IDEA**  IntelliJ IDEA 2022.3.2 (Community Edition)
*  **JAVA** OpenJDK 11

**Comment by Dmitryi1987** [comment]
Исправлено
